language: node_js
node_js:
 - "node"
notifications:
  email:
    - castano.julian@correounivalle.edu.co
jdk:
  - oraclejdk8
addons:
  sonarcloud: true
script:
  - npm run cover
  - sonar-scanner -Dsonar.login=$SONAR_CLOUD -Dsonar.organization=andresdfx-github -Dsonar.projectKey=datfin -Dsonar.sources='./routes' -X
after_success:
  - npm run coveralls
deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_API_KEY
  app: datfin

 

