language: node_js
node_js:
 - "node"
notifications:
  email:
    - castano.julian@correounivalle.edu.co
jdk:
  - oraclejdk8
addons:
 sonarcloud: true

cache:
  directories:
    - node_modules
script:
  - npm run test
  - sonar-scanner -Dsonar.login=$SONAR_CLOUD -Dsonar.organization=andresdfx-github -Dsonar.projectKey=datfin -Dsonar.sources='./routes' -X
  - npm prune 
  - npm prune --production
deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_API_KEY
  app: datfin



